
ENV_KEY_NACOS_SERVER_ADDR = "NACOS_SERVER_ADDR"
ENV_KEY_NACOS_USERNAME = "NACOS_USERNAME"
ENV_KEY_NACOS_PASSWORD = "NACOS_PASSWORD"
ENV_KEY_NACOS_NAMESPACE = "NACOS_CONFIG_NAMESPACE"
ENV_KEY_NACOS_CONFIG_DATA_ID = "NACOS_CONFIG_DATA_ID"
ENV_KEY_NACOS_CONFIG_GROUP = "NACOS_CONFIG_GROUP"
ENV_KEY_NACOS_CONFIG_TAG = "NACOS_CONFIG_TAG"
ENV_KEY_NACOS_CONFIG_TYPE = "NACOS_CONFIG_TYPE"
